import type { Metadata } from 'next'

import './globals.css'
import localFont from 'next/font/local'

const PPNeueMontreal = localFont({
  src: [
    {
      path: '../../public/fonts/pp-neue-montreal-regular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../../public/fonts/pp-neue-montreal-italic.woff2',
      weight: '400',
      style: 'italic',
    },
    {
      path: '../../public/fonts/pp-neue-montreal-medium.woff2',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../../public/fonts/pp-neue-montreal-medium-italic.woff2',
      weight: '500',
      style: 'italic',
    },
    {
      path: '../../public/fonts/pp-neue-montreal-bold.woff2',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../../public/fonts/pp-neue-montreal-bold-italic.woff2',
      weight: '700',
      style: 'italic',
    },
  ],
  variable: '--font-pp-neue-montreal',
  display: 'swap',
  fallback: ['sans-serif'],
})

export const metadata: Metadata = {
  title: 'Relume Design League - Joseph Berry Final Design',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${PPNeueMontreal.className} antialiased`}>
        {children}
      </body>
    </html>
  )
}
